### ISSUE TITLE
Allow sub-metrics filtering

### ISSUE THREAD

**Issue by jotak** [hawkular/hawkular-dropwizard-reporter#17]
Sub-metrics (ie. dropwizard metrics that are decomposed to several hawkular metrics, like "xxx.histogram.999perc") cannot be accurately filtered out using the dropwizard predicate functionality.

We should be able to filter them as well

**Comment by jotak** [comment]
@jsanda now that you have made more progress on C* metrics, would you say this enhancement is needed or not?

**Comment by jsanda** [comment]
Yes, this would be very useful; however, things are functional and working. I would love to see a release even before this feature is added and then hopefully get a PR submitted to metrics-reporter-config.

**Comment by jotak** [comment]
Ok, I try to see how to implement that... my fear is that adding a new filtering system, in addition to dropwizard's metric filter and addthis' black/white lists, will add confusion to the user.

**Comment by jotak** [comment]
@jsanda here's my proposal:
Since there's already dw filters and addthis' black/white lists, I suggest something less generic here, but allowing some control on how DW metrics are converted into H* metrics. Sample YAML we could have:

```yaml
hawkular:
  -
    metricsConversion:
      sample.metric.rate:
        - '1minrt'
        - 'meanrt'
      "/sample\\.metric\\.domain\\..*/":
        - '98perc'
        - '999perc'
```

ie., under property "metricsConversion" is a map of String (=metric name or regex) x white list of allowed decomposed parts.

In this example, we will have in Hawkular `sample.metric.rate.1minrt` , `sample.metric.rate.meanrt` but no `sample.metric.rate.5minrt`.

Sounds good to you?
